# CMake generated Testfile for 
# Source directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band
# Build directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/band
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_band_10_2_3_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/band/test_sunlinsol_band" "10" "2" "3" "0")
set_tests_properties(test_sunlinsol_band_10_2_3_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;107;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;0;")
add_test(test_sunlinsol_band_300_7_4_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/band/test_sunlinsol_band" "300" "7" "4" "0")
set_tests_properties(test_sunlinsol_band_300_7_4_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;107;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;0;")
add_test(test_sunlinsol_band_1000_8_8_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/band/test_sunlinsol_band" "1000" "8" "8" "0")
set_tests_properties(test_sunlinsol_band_1000_8_8_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;107;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;0;")
add_test(test_sunlinsol_band_5000_3_100_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/band/test_sunlinsol_band" "5000" "3" "100" "0")
set_tests_properties(test_sunlinsol_band_5000_3_100_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;107;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/band/CMakeLists.txt;0;")
