# CMake generated Testfile for 
# Source directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial
# Build directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/spgmr/serial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_spgmr_serial_100_1_1_100_1e-13_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "1" "1" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_1_1_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;115;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_2_1_100_1e-13_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "2" "1" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_2_1_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;115;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_1_2_100_1e-13_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "1" "2" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_1_2_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;115;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_2_2_100_1e-13_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "2" "2" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_2_2_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;115;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
