# CMake generated Testfile for 
# Source directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense
# Build directory: /Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/dense
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_dense_10_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/dense/test_sunlinsol_dense" "10" "0")
set_tests_properties(test_sunlinsol_dense_10_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;109;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_100_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/dense/test_sunlinsol_dense" "100" "0")
set_tests_properties(test_sunlinsol_dense_100_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;109;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_500_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/dense/test_sunlinsol_dense" "500" "0")
set_tests_properties(test_sunlinsol_dense_500_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;109;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
add_test(test_sunlinsol_dense_1000_0 "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/builddir/examples/sunlinsol/dense/test_sunlinsol_dense" "1000" "0")
set_tests_properties(test_sunlinsol_dense_1000_0 PROPERTIES  _BACKTRACE_TRIPLES "/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/config/SundialsAddTest.cmake;141;add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;109;sundials_add_test;/Users/satolab/Desktop/ShannonPigModel/Cpp_files/sundials/cvode-5.0.0/examples/sunlinsol/dense/CMakeLists.txt;0;")
